Sprint 12 develop
MelTrevelyan/java-filmorate pull request #21
Opened 2023-04-19 15:49 UTC by MelTrevelyan

2023-04-19 20:49 UTC, db-exp requested changes

2023-04-19 20:49 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getFilmsByDirectorOrTitle(@RequestParam String query, @RequestParam String by) {
Лучше проверить параметр на Null или сервис упадет с NPE

2023-04-19 20:49 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public List<Film> getFilmsByDirectorIdSortedByYearOrLikes(@PathVariable int directorId,
Лучше проверить параметры на Null или сервис упадет с NPE
Пример - https://stackoverflow.com/questions/24582842/is-it-possible-to-validate-requestparam-in-spring-mvc-rest-endpoint

2023-04-19 20:49 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/validator/FilmValidator.java
>          if (film.getReleaseDate().isBefore(LocalDate.of(1895, 12, 28))) {
напомню на всякий - можно сделать кастомную аннотацию https://blog.clairvoyantsoft.com/spring-boot-creating-a-custom-annotation-for-validation-edafbf9a97a4

2023-04-19 20:49 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/FilmDbStorage.java
> +        } catch (Exception e) {
тут лучше ловить конкретное исключение и бросать уже свое

2023-04-19 20:49 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final FilmStorage filmStorage;
лучше ходить не в соседние storage, а обращаться к ним через сервисы, чтобы уменьшить связность и иметь возможность не самим оборачивать бизнес логикой, а пользоваться общем
Комментарий справедлив для всех похожих случаев

2023-04-19 20:49 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/storage/dao/DirectorDbStorage.java
> +    private int nextId = 1;
если делать через "ручной" id, то в случае многопоточности начнутся коллизии
Лучше пользоваться https://www.baeldung.com/spring-jdbc-autogenerated-keys

2023-04-19 20:49 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private long nextId = 1;
нужно так - https://www.baeldung.com/spring-jdbc-autogenerated-keys

2023-04-19 20:49 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
>      private long nextId = 1;
нужно так https://www.baeldung.com/spring-jdbc-autogenerated-keys

2023-04-20 06:54 UTC, okoloTop commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>      private long nextId = 1;
Тут не совсем понял. Это же не моего стореджа касается,а присвоения id?

2023-04-20 21:14 UTC, db-exp approved these changes

2023-04-20 21:14 UTC, db-exp commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        AtomicReference<String> director = new AtomicReference<>("");
не понял если честно зачем тут Atomic

2023-04-21 01:50 UTC, merged

2023-04-21 07:25 UTC, Leno4kaG commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        AtomicReference<String> director = new AtomicReference<>("");
Потому как используем в лямбда выражении, в связи с многопоточностью.